/*
  This code is itself loaded by header code generated by function header() in pj.
  Other modules are then loaded by invoking us.
*/
karl.load = function(module) {
  /* module = name of module without the ".js" */
  if (karl.modules_loaded[module]==1) {return} /* already loaded, don't load again */
  load(module+".js");
  karl.modules_loaded[module]=1;
};
