#!/usr/bin/ruby

code = <<CODE
T:sqrt(abs_ell)*exp(r/2)*sc(t/2)$
X:sqrt(abs_ell)*exp(r/2)*cs(t/2)$
V:T+X$
W:T-X$
j:jacobian([V,W],[t,r])$
print("region 1 1 ",string(j[1,1]));
print("region 1 2 ",string(j[1,2]));
print("region 2 1 ",string(j[2,1]));
print("region 2 2 ",string(j[2,2]));
CODE

print "/* This code was generated by jacobian.rb. */\n"
1.upto(4) { |region|
  c = code.clone
  if region==1 || region==3 then
    # exterior
    c.gsub!("abs_ell") {"r-1"}
    c.gsub!("sc") {"sinh"}
    c.gsub!("cs") {"cosh"}
  else
    # interior
    c.gsub!("abs_ell") {"1-r"}
    c.gsub!("sc") {"cosh"}
    c.gsub!("cs") {"sinh"}
  end
  c.gsub!("region") {region}
  print c
}

