christoffel:
	maxima -b christoffel.mac
	# Now cut and paste output into maxima/clean_up_christoffel.rb and run it.

jacobian:
	jacobian.rb >jacobian.mac
	maxima --very-quiet -r "load(\"jacobian.mac\")$$"
	# Now cut and paste output into maxima/clean_up_jacobian.rb and run it.

